class FishTankRunner{
public static void main(String[] args){
		FishTank instance1=new FishTank("Glass",100.0,60.0,30.0,40.0,"Rectangle",true,true,1,false,"Aqua");
		System.out.println("material:"+instance1.material);
		System.out.println("capacity:"+instance1.capacity);
		System.out.println("length:"+instance1.length);
		System.out.println("width:"+instance1.width);
		System.out.println("height:"+instance1.height);
		System.out.println("shape:"+instance1.shape);
		System.out.println("hasFilter:"+instance1.hasFilter);
		System.out.println("hasLight:"+instance1.hasLight);
		System.out.println("tankId:"+instance1.tankId);
		System.out.println("isSaltWater:"+instance1.isSaltWater);
		System.out.println("brand:"+instance1.brand);

		FishTank instance2=new FishTank("Plastic",80.0,50.0,25.0,35.0,"Square",true,false,2,true,"Oceanic");
		System.out.println("material:"+instance2.material);
		System.out.println("capacity:"+instance2.capacity);
		System.out.println("length:"+instance2.length);
		System.out.println("width:"+instance2.width);
		System.out.println("height:"+instance2.height);
		System.out.println("shape:"+instance2.shape);
		System.out.println("hasFilter:"+instance2.hasFilter);
		System.out.println("hasLight:"+instance2.hasLight);
		System.out.println("tankId:"+instance2.tankId);
		System.out.println("isSaltWater:"+instance2.isSaltWater);
		System.out.println("brand:"+instance2.brand);

		FishTank instance3=new FishTank("Acrylic",120.0,70.0,35.0,45.0,"Rectangle",false,true,3,false,"BlueSea");
		System.out.println("material:"+instance3.material);
		System.out.println("capacity:"+instance3.capacity);
		System.out.println("length:"+instance3.length);
		System.out.println("width:"+instance3.width);
		System.out.println("height:"+instance3.height);
		System.out.println("shape:"+instance3.shape);
		System.out.println("hasFilter:"+instance3.hasFilter);
		System.out.println("hasLight:"+instance3.hasLight);
		System.out.println("tankId:"+instance3.tankId);
		System.out.println("isSaltWater:"+instance3.isSaltWater);
		System.out.println("brand:"+instance3.brand);

		FishTank instance4=new FishTank("Glass",150.0,80.0,40.0,50.0,"Round",true,true,4,true,"AquaPro");
		System.out.println("material:"+instance4.material);
		System.out.println("capacity:"+instance4.capacity);
		System.out.println("length:"+instance4.length);
		System.out.println("width:"+instance4.width);
		System.out.println("height:"+instance4.height);
		System.out.println("shape:"+instance4.shape);
		System.out.println("hasFilter:"+instance4.hasFilter);
		System.out.println("hasLight:"+instance4.hasLight);
		System.out.println("tankId:"+instance4.tankId);
		System.out.println("isSaltWater:"+instance4.isSaltWater);
		System.out.println("brand:"+instance4.brand);

		FishTank instance5=new FishTank("Plastic",60.0,40.0,20.0,30.0,"Square",false,false,5,false,"MiniTank");
		System.out.println("material:"+instance5.material);
		System.out.println("capacity:"+instance5.capacity);
		System.out.println("length:"+instance5.length);
		System.out.println("width:"+instance5.width);
		System.out.println("height:"+instance5.height);
		System.out.println("shape:"+instance5.shape);
		System.out.println("hasFilter:"+instance5.hasFilter);
		System.out.println("hasLight:"+instance5.hasLight);
		System.out.println("tankId:"+instance5.tankId);
		System.out.println("isSaltWater:"+instance5.isSaltWater);
		System.out.println("brand:"+instance5.brand);

		FishTank instance6=new FishTank("Glass",200.0,90.0,45.0,55.0,"Rectangle",true,true,6,true,"OceanPlus");
		System.out.println("material:"+instance6.material);
		System.out.println("capacity:"+instance6.capacity);
		System.out.println("length:"+instance6.length);
		System.out.println("width:"+instance6.width);
		System.out.println("height:"+instance6.height);
		System.out.println("shape:"+instance6.shape);
		System.out.println("hasFilter:"+instance6.hasFilter);
		System.out.println("hasLight:"+instance6.hasLight);
		System.out.println("tankId:"+instance6.tankId);
		System.out.println("isSaltWater:"+instance6.isSaltWater);
		System.out.println("brand:"+instance6.brand);

		FishTank instance7=new FishTank("Acrylic",140.0,75.0,38.0,48.0,"Hexagon",true,false,7,false,"AquaHex");
		System.out.println("material:"+instance7.material);
		System.out.println("capacity:"+instance7.capacity);
		System.out.println("length:"+instance7.length);
		System.out.println("width:"+instance7.width);
		System.out.println("height:"+instance7.height);
		System.out.println("shape:"+instance7.shape);
		System.out.println("hasFilter:"+instance7.hasFilter);
		System.out.println("hasLight:"+instance7.hasLight);
		System.out.println("tankId:"+instance7.tankId);
		System.out.println("isSaltWater:"+instance7.isSaltWater);
		System.out.println("brand:"+instance7.brand);

		FishTank instance8=new FishTank("Glass",110.0,65.0,32.0,42.0,"Rectangle",false,true,8,true,"BlueWave");
		System.out.println("material:"+instance8.material);
		System.out.println("capacity:"+instance8.capacity);
		System.out.println("length:"+instance8.length);
		System.out.println("width:"+instance8.width);
		System.out.println("height:"+instance8.height);
		System.out.println("shape:"+instance8.shape);
		System.out.println("hasFilter:"+instance8.hasFilter);
		System.out.println("hasLight:"+instance8.hasLight);
		System.out.println("tankId:"+instance8.tankId);
		System.out.println("isSaltWater:"+instance8.isSaltWater);
		System.out.println("brand:"+instance8.brand);

		FishTank instance9=new FishTank("Plastic",70.0,45.0,22.0,32.0,"Round",true,false,9,false,"MiniAqua");
		System.out.println("material:"+instance9.material);
		System.out.println("capacity:"+instance9.capacity);
		System.out.println("length:"+instance9.length);
		System.out.println("width:"+instance9.width);
		System.out.println("height:"+instance9.height);
		System.out.println("shape:"+instance9.shape);
		System.out.println("hasFilter:"+instance9.hasFilter);
		System.out.println("hasLight:"+instance9.hasLight);
		System.out.println("tankId:"+instance9.tankId);
		System.out.println("isSaltWater:"+instance9.isSaltWater);
		System.out.println("brand:"+instance9.brand);

		FishTank instance10=new FishTank("Glass",180.0,85.0,42.0,52.0,"Rectangle",true,true,10,true,"AquaMax");
		System.out.println("material:"+instance10.material);
		System.out.println("capacity:"+instance10.capacity);
		System.out.println("length:"+instance10.length);
		System.out.println("width:"+instance10.width);
		System.out.println("height:"+instance10.height);
		System.out.println("shape:"+instance10.shape);
		System.out.println("hasFilter:"+instance10.hasFilter);
		System.out.println("hasLight:"+instance10.hasLight);
		System.out.println("tankId:"+instance10.tankId);
		System.out.println("isSaltWater:"+instance10.isSaltWater);
		System.out.println("brand:"+instance10.brand);

		FishTank instance11=new FishTank("Acrylic",130.0,72.0,36.0,46.0,"Square",false,true,11,false,"ClearView");
		System.out.println("material:"+instance11.material);
		System.out.println("capacity:"+instance11.capacity);
		System.out.println("length:"+instance11.length);
		System.out.println("width:"+instance11.width);
		System.out.println("height:"+instance11.height);
		System.out.println("shape:"+instance11.shape);
		System.out.println("hasFilter:"+instance11.hasFilter);
		System.out.println("hasLight:"+instance11.hasLight);
		System.out.println("tankId:"+instance11.tankId);
		System.out.println("isSaltWater:"+instance11.isSaltWater);
		System.out.println("brand:"+instance11.brand);

		FishTank instance12=new FishTank("Glass",95.0,58.0,29.0,39.0,"Rectangle",true,false,12,true,"SeaLife");
		System.out.println("material:"+instance12.material);
		System.out.println("capacity:"+instance12.capacity);
		System.out.println("length:"+instance12.length);
		System.out.println("width:"+instance12.width);
		System.out.println("height:"+instance12.height);
		System.out.println("shape:"+instance12.shape);
		System.out.println("hasFilter:"+instance12.hasFilter);
		System.out.println("hasLight:"+instance12.hasLight);
		System.out.println("tankId:"+instance12.tankId);
		System.out.println("isSaltWater:"+instance12.isSaltWater);
		System.out.println("brand:"+instance12.brand);

		FishTank instance13=new FishTank("Plastic",55.0,38.0,18.0,28.0,"Square",false,false,13,false,"NanoTank");
		System.out.println("material:"+instance13.material);
		System.out.println("capacity:"+instance13.capacity);
		System.out.println("length:"+instance13.length);
		System.out.println("width:"+instance13.width);
		System.out.println("height:"+instance13.height);
		System.out.println("shape:"+instance13.shape);
		System.out.println("hasFilter:"+instance13.hasFilter);
		System.out.println("hasLight:"+instance13.hasLight);
		System.out.println("tankId:"+instance13.tankId);
		System.out.println("isSaltWater:"+instance13.isSaltWater);
		System.out.println("brand:"+instance13.brand);

		FishTank instance14=new FishTank("Glass",210.0,95.0,48.0,58.0,"Rectangle",true,true,14,true,"OceanKing");
		System.out.println("material:"+instance14.material);
		System.out.println("capacity:"+instance14.capacity);
		System.out.println("length:"+instance14.length);
		System.out.println("width:"+instance14.width);
		System.out.println("height:"+instance14.height);
		System.out.println("shape:"+instance14.shape);
		System.out.println("hasFilter:"+instance14.hasFilter);
		System.out.println("hasLight:"+instance14.hasLight);
		System.out.println("tankId:"+instance14.tankId);
		System.out.println("isSaltWater:"+instance14.isSaltWater);
		System.out.println("brand:"+instance14.brand);

		FishTank instance15=new FishTank("Acrylic",160.0,78.0,39.0,49.0,"Hexagon",true,false,15,false,"HexaPro");
		System.out.println("material:"+instance15.material);
		System.out.println("capacity:"+instance15.capacity);
		System.out.println("length:"+instance15.length);
		System.out.println("width:"+instance15.width);
		System.out.println("height:"+instance15.height);
		System.out.println("shape:"+instance15.shape);
		System.out.println("hasFilter:"+instance15.hasFilter);
		System.out.println("hasLight:"+instance15.hasLight);
		System.out.println("tankId:"+instance15.tankId);
		System.out.println("isSaltWater:"+instance15.isSaltWater);
		System.out.println("brand:"+instance15.brand);

		FishTank instance16=new FishTank("Glass",175.0,82.0,41.0,51.0,"Rectangle",true,true,16,true,"AquaElite");
		System.out.println("material:"+instance16.material);
		System.out.println("capacity:"+instance16.capacity);
		System.out.println("length:"+instance16.length);
		System.out.println("width:"+instance16.width);
		System.out.println("height:"+instance16.height);
		System.out.println("shape:"+instance16.shape);
		System.out.println("hasFilter:"+instance16.hasFilter);
		System.out.println("hasLight:"+instance16.hasLight);
		System.out.println("tankId:"+instance16.tankId);
		System.out.println("isSaltWater:"+instance16.isSaltWater);
		System.out.println("brand:"+instance16.brand);

		FishTank instance17=new FishTank("Plastic",65.0,42.0,21.0,31.0,"Round",false,false,17,false,"BasicTank");
		System.out.println("material:"+instance17.material);
		System.out.println("capacity:"+instance17.capacity);
		System.out.println("length:"+instance17.length);
		System.out.println("width:"+instance17.width);
		System.out.println("height:"+instance17.height);
		System.out.println("shape:"+instance17.shape);
		System.out.println("hasFilter:"+instance17.hasFilter);
		System.out.println("hasLight:"+instance17.hasLight);
		System.out.println("tankId:"+instance17.tankId);
		System.out.println("isSaltWater:"+instance17.isSaltWater);
		System.out.println("brand:"+instance17.brand);

		FishTank instance18=new FishTank("Acrylic",145.0,74.0,37.0,47.0,"Square",true,true,18,true,"CrystalClear");
		System.out.println("material:"+instance18.material);
		System.out.println("capacity:"+instance18.capacity);
		System.out.println("length:"+instance18.length);
		System.out.println("width:"+instance18.width);
		System.out.println("height:"+instance18.height);
		System.out.println("shape:"+instance18.shape);
		System.out.println("hasFilter:"+instance18.hasFilter);
		System.out.println("hasLight:"+instance18.hasLight);
		System.out.println("tankId:"+instance18.tankId);
		System.out.println("isSaltWater:"+instance18.isSaltWater);
		System.out.println("brand:"+instance18.brand);

		FishTank instance19=new FishTank("Glass",125.0,68.0,34.0,44.0,"Rectangle",false,true,19,false,"BlueOcean");
		System.out.println("material:"+instance19.material);
		System.out.println("capacity:"+instance19.capacity);
		System.out.println("length:"+instance19.length);
		System.out.println("width:"+instance19.width);
		System.out.println("height:"+instance19.height);
		System.out.println("shape:"+instance19.shape);
		System.out.println("hasFilter:"+instance19.hasFilter);
		System.out.println("hasLight:"+instance19.hasLight);
		System.out.println("tankId:"+instance19.tankId);
		System.out.println("isSaltWater:"+instance19.isSaltWater);
		System.out.println("brand:"+instance19.brand);

		FishTank instance20=new FishTank("Glass",220.0,100.0,50.0,60.0,"Rectangle",true,true,20,true,"MegaAqua");
		System.out.println("material:"+instance20.material);
		System.out.println("capacity:"+instance20.capacity);
		System.out.println("length:"+instance20.length);
		System.out.println("width:"+instance20.width);
		System.out.println("height:"+instance20.height);
		System.out.println("shape:"+instance20.shape);
		System.out.println("hasFilter:"+instance20.hasFilter);
		System.out.println("hasLight:"+instance20.hasLight);
		System.out.println("tankId:"+instance20.tankId);
		System.out.println("isSaltWater:"+instance20.isSaltWater);
		System.out.println("brand:"+instance20.brand);
		}
		}
		